/// <reference types='cypress' />

describe('Validar links institucionais', () => {
 beforeEach(() => {
  cy.visit('https://www.viacaocometa.com.br');
});
it('Validar links informações de Viagem - Bagagem', () => {
  cy.get('.header-nav-container > :nth-child(1) > :nth-child(1) > .focusable').click()
  cy.url().should('include', 'informacao-para-sua-viagem')
  cy.get('.aem-Grid--12 > :nth-child(4) > .custom-padding > .container > :nth-child(1) > .aem-Grid > .image > .cmp-image > #cmp-image-link > .cmp-image__image').click()
  cy.get('#bagagemdemao > p').should('contain', 'Bagagem de mão')
  cy.scrollTo('top')
  cy.wait(1000)
  cy.get('[href="#bagagemdespachada"] > .btn-title').click()
  cy.get('#bagagemdespachada > [style="text-align: left;"]').should('contain', 'Bagagem despachada no bagageiro')
  cy.scrollTo('top')
  cy.wait(1000)
  cy.get('[href="#bagagemproibida"]').click()
  cy.get('#bagagemproibida > p').should('contain', 'Bagagem proibida')
  cy.scrollTo('top')
  cy.wait(1000)
  cy.get('[href="#bagagensespeciaiseesportivas"] > .btn-title').click()
  cy.get('#bagagensespeciaiseesportivas > p').should('contain', 'Bagagens especiais e esportivas')
  cy.scrollTo('top')
  cy.wait(1000)
  cy.get('[href="#bagagensextraviadas"] > .btn-title').click()
  cy.get('#bagagensextraviadas > p').should('contain', 'Bagagens extraviadas ou danificadas')
  cy.scrollTo('top')
  cy.wait(1000)
  cy.get('[href="#objetosesquecidos"] > .btn-title').click()
  cy.get('#objetosesquecidos > p').should('contain', 'Objetos esquecidos no interior do veículo')
  cy.scrollTo('top')
  cy.wait(1000)
  cy.get('[href="#cobranca"] > .btn-title').click()
  cy.get('#cobranca > p').should('contain', 'Cobrança por excesso de bagagem')
  })

  it('Validar links informações de Viagem - Informações para embarque', () => {
    cy.get('.header-nav-container > :nth-child(1) > :nth-child(1) > .focusable').click()
    cy.url().should('include', 'informacao-para-sua-viagem')
    cy.get('.aem-Grid--12 > :nth-child(5) > .custom-padding > .container > :nth-child(1) > .aem-Grid > .image > .cmp-image > #cmp-image-link > .cmp-image__image').click()
    cy.get('[href="#documentacaoparaembarque"] > .btn-title').click()
    cy.get('#documentacaoparaembarque > p').should('contain', 'Documentação para embarque')
    cy.scrollTo('top')
    cy.wait(1000)
    cy.get('[href="#embarqueparamenores"] > .btn-title').click()
    cy.get('#embarqueparamenores > p').should('contain', 'Embarque para Menores')
    cy.scrollTo('top')
    cy.wait(1000)
    cy.get('[href="#horariodeembarque"]').click()
    cy.get('#horariodeembarque > p').should('contain', 'Horário de embarque')
    cy.scrollTo('top')
    cy.wait(1000)
    cy.get('[href="#transportedeanimais"]').click()
    cy.get('#transportedeanimais > p').should('contain', 'Transporte de Animais')
    cy.scrollTo('top')
    cy.wait(1000)
    cy.get('[href="#segurofacultativo"]').click()
    cy.get('#segurofacultativo > p').should('contain', 'Seguro Facultativo')
    cy.scrollTo('top')
    cy.wait(1000)
    cy.get('[href="#alteracoesdehorario"]').click()
    cy.get('#alteracoesdehorario > p').should('contain', 'Alterações de Horários e Frequências')
    cy.scrollTo('top')
  });

  it('Validar links informações de Viagem - Compra, remarcação e reembolso', () => {
    cy.get('.header-nav-container > :nth-child(1) > :nth-child(1) > .focusable').click()
    cy.url().should('include', 'informacao-para-sua-viagem')
    cy.get('[style="padding: 0rem 2rem 2rem 2rem "] > :nth-child(1) > .aem-Grid--12 > :nth-child(1) > .custom-padding > .container > :nth-child(1) > .aem-Grid > .image > .cmp-image > #cmp-image-link > .cmp-image__image').click()
    cy.get('[href="#formasdepagamento"]').click()
    cy.get('#formasdepagamento > p').should('contain', 'Formas de Pagamento')
    cy.scrollTo('top')
    cy.wait(1000)
    cy.get('[href="#remarcacaoetroca"]').click()
    cy.get('#remarcacaoetroca > p').should('contain', 'Remarcação e Troca')
    cy.scrollTo('top')
    cy.wait(1000)
    cy.get('[href="#cancelamentoereembolso"]').click()
    cy.get('#cancelamentoereembolso > p').should('contain', 'Cancelamento e Reembolso')
    cy.scrollTo('top')
    cy.wait(1000)
    cy.get('[href="#reacomodacao"]').click()
    cy.get('#reacomodacao > p').should('contain', 'Reacomodações')
    cy.scrollTo('top')
    cy.wait(1000)
    cy.get('[href="#taxas"]').click()
    cy.get('#taxas > p').should('contain', 'Taxas de serviços')
    cy.scrollTo('top')
  });

it('Validar links informações de Viagem - Nossos serviços', () => {
    cy.get('.header-nav-container > :nth-child(1) > :nth-child(1) > .focusable').click()
    cy.url().should('include', 'informacao-para-sua-viagem')
    cy.get(':nth-child(2) > .custom-padding > .container > :nth-child(1) > .aem-Grid > .image > .cmp-image > #cmp-image-link > .cmp-image__image').click()
    cy.get('[href="#nossosonibus"]').click()
    cy.get('#nossosonibus > p').should('contain', 'Conheça Nossos Ônibus')
    cy.scrollTo('top')
    cy.wait(1000)
    cy.get('[href="#salasvips"]').click()
    cy.get('#salasvips > p').should('contain', 'SALAS VIPS')
    cy.scrollTo('top')
    cy.wait(1000)
    cy.get('[href="#salasnets"]').click()
    cy.get('[style="margin: auto auto auto auto "] > [style="padding: 2rem 2rem 2rem 2rem "] > :nth-child(1) > .aem-Grid--phone--12 > :nth-child(1) > #salasnets > p').should('contain', 'SALAS NETS')
    cy.scrollTo('top')
    cy.wait(1000)
    cy.get('[href="#clubegiro"]').click()
    cy.get('#clubegiro > [style="padding: 2rem 2rem 2rem 2rem "] > :nth-child(1) > .aem-Grid--phone--12 > :nth-child(1) > #salasnets > p').should('contain', 'CLUBE GIRO')

  });

  it('Validar links informações de Viagem - Descontos e Gratuidades', () => {
    cy.get('.header-nav-container > :nth-child(1) > :nth-child(1) > .focusable').click()
    cy.url().should('include', 'informacao-para-sua-viagem')
    cy.get(':nth-child(4) > :nth-child(2) > :nth-child(2) > :nth-child(1) > .aem-Grid--12 > .cmp > .custom-padding > .container > :nth-child(1) > .aem-Grid > .image > .cmp-image > #cmp-image-link > .cmp-image__image').click()
    cy.get('[href="#estudante"]').click()
    cy.get('#estudante > p').should('contain', 'Estudante e Professor')
    cy.scrollTo('top')
    cy.wait(1000)
    cy.get('[href="#PCD"]').click()
    cy.get('#PCD > p').should('contain', 'Pessoa com deficiência')
    cy.scrollTo('top')
    cy.wait(1000)
    cy.get('[href="#idoso"]').click()
    cy.get('#idoso > p').should('contain', 'Idoso')
    cy.scrollTo('top')
    cy.wait(1000)
    cy.get('[href="#IDJovem"]').click()
    cy.get('#IDJovem > p').should('contain', 'ID Jovem')
  });
});