name: Monitoramento Contínuo Cypress
on:
  push:
    branches: [ main, master ]

  schedule:
    - cron: '*/59 * * * *'
    - cron: '0 20 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [1, 2 , 3]
        node-version: [24]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar Dependências
        run: npm install

      - name: Dar permissão ao Cypress
        run: chmod +x ./node_modules/.bin/cypress

      - name: Rodar Testes Cypress
        id: cypress
        continue-on-error: true
        run: npx cypress run --spec "cypress/e2e/00_smoke/**/*"
        env:
          LOGIN: ${{ secrets.LOGIN }}
          SENHA: ${{ secrets.SENHA }}
          
          
          # NOVO PASSO: Salvar o Relatório Mochawesome
      - name: Salvar Relatório HTML
        if: always() # Garante que o relatório seja salvo mesmo se o teste falhar
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-cypress
          path: cypress/reports/
          retention-days: 7 # O link expira em 7 dias para não ocupar seu espaço

      - name: Enviar E-mail de SUCESSO ✅
        if: |
          steps.cypress.outcome == 'success' && 
          (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event.schedule == '0 20 * * *')
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "✅ (EM TESTE) Monitoramento Cypress - Viação Cometa"
          to: anderson.ssantos@jcatlm.com.br
          from: "Monitoramento Contínuo Cypress"
          body: |
            RELATÓRIO DE SUCESSO 🚀 Monitoramento Cypress - Viação Cometa

            📊 O relatório detalhado (Mochawesome) está disponível na aba "Artifacts" do link abaixo.
            🔗 LINK: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Todos os testes passaram com sucesso! 🚀
            Os fluxos login, busca de passagens, conta giro, links do header e footer estão funcionando corretamente.

            ---
            🔹 GATILHO: ${{ github.event_name == 'schedule' && 'Agendamento Automático' || github.event_name == 'push' && 'Novo Código (Push)' || 'Execução Manual' }}
            🔹 STATUS: Todos os testes passaram!
            🔹 REPOSITÓRIO: ${{ github.repository }}
            🔹 BRANCH: ${{ github.ref_name }}
            ---
            Detalhes da execução: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Enviar E-mail de FALHA 🚨
        if: steps.cypress.outcome == 'failure'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "🚨 (EM TESTE) (FALHA) Relatório Cypress - Viação Cometa"
          to: anderson.ssantos@jcatlm.com.br
          from: "Monitoramento Contínuo Cypress"
          body: |
            RELATÓRIO DE FALHA DETECTADA 🚨

             📊 O relatório detalhado (Mochawesome) está disponível na aba "Artifacts" do link abaixo.
            🔗 LINK: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            ---
            ❌ GATILHO DO ERRO: ${{ github.event_name == 'schedule' && 'Agendamento Automático' || github.event_name == 'push' && 'Novo Código (Push)' || 'Execução Manual' }}
            ❌ EXECUTADO POR: ${{ github.actor }}
            ❌ DATA/HORA: ${{ github.event.head_commit.timestamp || 'Horário agendado' }}
            ---
            
            RESUMO DOS TESTES:
            O Cypress encontrou um erro durante a execução das specs. 
            Isso pode indicar que o site da Viação Cometa está instável ou houve uma falha no processo de login.
            
            COMO ANALISAR:
            1. Acesse o link abaixo.
            2. Vá na aba "Artifacts" para baixar o Vídeo ou Screenshot do erro.
            3. Verifique o log do passo "Rodar Testes Cypress".
            
            🔗 LINK DO RELATÓRIO: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
